networks:
  piscineds:

services:
  db:
    image: postgres:17
    container_name: postgres_db_04
    networks:
      - piscineds
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
# volumes:
#   - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_04
    networks:
      - piscineds
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db
    
  importer:
    build: ./it_importer
    networks:
      - piscineds
    env_file:
      - .env
    volumes:
      - ./item:/app/item
    restart: no
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
